# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tieuDe = QtWidgets.QLabel(self.centralwidget)
        self.tieuDe.setGeometry(QtCore.QRect(350, 0, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.tieuDe.setFont(font)
        self.tieuDe.setObjectName("tieuDe")
        self.plaintext = QtWidgets.QLabel(self.centralwidget)
        self.plaintext.setGeometry(QtCore.QRect(20, 130, 60, 16))
        self.plaintext.setObjectName("plaintext")
        self.ciphertext = QtWidgets.QLabel(self.centralwidget)
        self.ciphertext.setGeometry(QtCore.QRect(20, 290, 81, 16))
        self.ciphertext.setObjectName("ciphertext")
        self.information = QtWidgets.QLabel(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(470, 130, 71, 16))
        self.information.setObjectName("information")
        self.signature = QtWidgets.QLabel(self.centralwidget)
        self.signature.setGeometry(QtCore.QRect(470, 280, 60, 16))
        self.signature.setObjectName("signature")
        self.txt_plaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plaintext.setGeometry(QtCore.QRect(100, 110, 311, 78))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.txt_ciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_ciphertext.setGeometry(QtCore.QRect(100, 260, 321, 78))
        self.txt_ciphertext.setObjectName("txt_ciphertext")
        self.txt_information = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_information.setGeometry(QtCore.QRect(550, 120, 321, 78))
        self.txt_information.setObjectName("txt_information")
        self.txt_signature = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_signature.setGeometry(QtCore.QRect(550, 260, 321, 78))
        self.txt_signature.setObjectName("txt_signature")
        self.bt_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bt_encrypt.setGeometry(QtCore.QRect(100, 430, 113, 32))
        self.bt_encrypt.setObjectName("bt_encrypt")
        self.bt_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bt_decrypt.setGeometry(QtCore.QRect(310, 430, 113, 32))
        self.bt_decrypt.setObjectName("bt_decrypt")
        self.bt_sign = QtWidgets.QPushButton(self.centralwidget)
        self.bt_sign.setGeometry(QtCore.QRect(550, 440, 113, 32))
        self.bt_sign.setObjectName("bt_sign")
        self.bt_verity = QtWidgets.QPushButton(self.centralwidget)
        self.bt_verity.setGeometry(QtCore.QRect(780, 440, 113, 32))
        self.bt_verity.setObjectName("bt_verity")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 70, 113, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tieuDe.setText(_translate("MainWindow", "RSA CIPHER"))
        self.plaintext.setText(_translate("MainWindow", "Plain text"))
        self.ciphertext.setText(_translate("MainWindow", "Cipher text"))
        self.information.setText(_translate("MainWindow", "Information"))
        self.signature.setText(_translate("MainWindow", "Signature"))
        self.bt_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.bt_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.bt_sign.setText(_translate("MainWindow", "Sign"))
        self.bt_verity.setText(_translate("MainWindow", "Verity"))
        self.pushButton_5.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
